version: '2.1'

services:
    nginx:
        container_name: streaming-nginx
        image: nginx:stable
        #build:
        #    context: ./docker/nginx-vod
        ports:
            - "80:80"
            - "433:433"

